### ISSUE TITLE
Make the soft offline too

### ISSUE THREAD

**Issue by chronoss09** [friendlyanon/CFW2OFW-Helper#1]
Sorry but i don't know how to make the pull request :(

1- In version 3, i can launch the soft without internet but with in version 4, it requiert internet to launch it :(

2- Is it possible to make the soft offline to convert the game if i have the patch of the game ?

3- Make the soft to duplicate the game and not to delete the source folder after converting...

4- We need just one EBOOT.BIN for the patch to convert the game, why it download all patch of the game for just one EBOOT.BIN ?

**Comment by friendlyanon** [comment]
Since the program is still not considered finished, the mandatory update check on startup has to be there to ensure people are using the latest version always. This is to prevent issues with people reporting different issues from different versions.
At the moment, the program is strictly online-only, because it gathers information from the update XML like the possibility of conversion at all, the URL to the updates and the sha1 checksum to confirm the integrity of the updates that is checked when the patch is found in the offline `patch` directory.
Options and a configuration UI are planned, which will include offline only mode, the possibility of cloning the game instead of consuming it in the conversion process, etc. You are right on that I should have notified users that the program consumes the game in the conversion process, but for now you'll just have to make sure to COPY the game in the working folder of the program and not MOVE it.
Also, if I knew exactly what is needed for the conversion besides the EBOOT.BIN, I'd gladly refactor my code to comply with the proper needs of converting games successfully, but as it stands now, all the information is scattered and partially available. This is a sad fact, but almost nothing is properly documented that is not already on the PSDevWiki.
If you can provide proper documentation that details what is needed exactly to convert a game to be compatible with DTU or TABR exploits then please do, because that would help everyone.

**Comment by friendlyanon** [comment]
Your 3rd point is covered with the release of `v8`, so I'm closing this for now.
The rest should also slowly make their way into the program.

**Comment by chronoss09** [comment]
Ok thanks :)
