### ISSUE TITLE
You should never be able to see this message.

### ISSUE THREAD

**Issue by Jimmy-Z** [friendlyanon/CFW2OFW-Helper#5]
Trying to check game compatibility.

`"CFW2OFW Helper.exe" BCAS25005`

````
--- CFW2OFW Helper v6 ---

Game identified: BCAS25005

You should never be able to see this message.
Press any key to exit . . .
````

**Comment by ErikPshat** [comment]
BCAS25005 - Updates not available for FINAL FANTASY® XIII

**Comment by friendlyanon** [comment]
Version 7 gives you a clearer message in this scenario.
Weird, because in my testings this error never came up, but added an error handler just in case and this is why I thought I'd be funny and make a [reference to this](https://www.youtube.com/watch?v=7a9N0k35jak).

But yes, that error message means there is no update available for the title and thus it's incompatible.
